# Generated by Django 5.2.6 on 2025-09-20 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_initial'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='records.heartraterecord'),
        ),
    ]
